name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'

    - name: Find package.json
      id: find-package
      run: |
        PACKAGE_PATH=$(find . -name "package.json" -not -path "*/node_modules/*" | head -n 1)
        if [ -z "$PACKAGE_PATH" ]; then
          echo "No package.json found"
          exit 1
        fi
        echo "::set-output name=package_path::$(dirname $PACKAGE_PATH)"

    - name: Install dependencies
      run: npm install
      working-directory: ${{ steps.find-package.outputs.package_path }}

    - name: Run tests
      run: npm test
      working-directory: ${{ steps.find-package.outputs.package_path }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: success()

    - name: Build Docker image
      uses: docker/build-push-action@v2
      if: success()
      with:
        context: ${{ steps.find-package.outputs.package_path }}
        push: false
        tags: my-node-app:latest
        file: ${{ steps.find-package.outputs.package_path }}/Dockerfile