name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd capstone_project && \
          cd hello* && \
          npm install

      - name: Run tests
        run: |
          cd capstone_project && \
          cd hello* && \
          npm test

      - name: Build container
        if: success()
        run: |
          cd capstone_project && \
          cd hello* && \
          docker build -t welcome-to-docker .